expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Expense, Category
from .views import ExpenseListView, CategoryListView


urlpatterns = [
    path('expense/list/',
         ExpenseListView.as_view(),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
            model=Expense,
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_delete.html'
         ),
         name='expense-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('category/create/',
         CreateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-create'),

    path('category/<int:pk>/edit/',
         UpdateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-edit'),

    path('category/<int:pk>/delete/',
         DeleteView.as_view(
            model=Category,
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_delete.html'
         ),
         name='category-delete'),
]

project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')),
]

expenses/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk')

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)

    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

expenses/forms.py
from django import forms
from .models import Expense, Category


class DateInput(forms.DateInput):
    input_type = 'date'

class ExpenseSearchForm(forms.ModelForm):
    CHOICES = [(category.id, category) 
               for category in Category.objects.all()]
    ORDER_CHOICES = (
        ("1", "Latest"),
        ("2", "Oldest"),
        ("3", "Category Up"),
        ("4", "Category Down"),
        )
    class Meta:
        model = Expense
        fields = ('name',)
    # name = forms.CharField(label='Your name')
    min_date = forms.DateField(label='From', widget=DateInput, required=False)
    max_date = forms.DateField(label='To', widget=DateInput, required=False)
    category = forms.MultipleChoiceField(choices=(CHOICES), widget=forms.CheckboxSelectMultiple, required=False)
    order = forms.ChoiceField(choices=ORDER_CHOICES, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False

expenses/views.py
from django.views.generic.list import ListView

from .forms import ExpenseSearchForm
from .models import Expense, Category
from .reports import summary_per_category, summary_per_date

from django.db.models import Sum

class ExpenseListView(ListView):
    model = Expense
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list
        total = Expense.objects.aggregate(Sum('amount'))["amount__sum"]
        print(total)
        form = ExpenseSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get('name', '').strip()
            min_date = form.cleaned_data.get('min_date')
            max_date = form.cleaned_data.get('max_date')
            if name:
                queryset = queryset.filter(name__icontains=name)
            if min_date:
                queryset = queryset.filter(date__gte=min_date)
            if max_date:
                queryset = queryset.filter(date__lte=max_date)
            category = form.cleaned_data.get('category')
            if category:
                queryset = queryset.filter(category__id__in=category)
            order = form.cleaned_data.get('order')
            if order:
                if order == "1":
                    queryset = queryset.order_by('-date')
                elif order == "2":
                    queryset = queryset.order_by('date')
                elif order == "3":
                    queryset = queryset.order_by('category')
                elif order == "4":
                    queryset = queryset.order_by('-category')

        return super().get_context_data(
            form=form,
            object_list=queryset,
            summary_per_category=summary_per_category(queryset),
            summary_per_date=summary_per_date(),
            total=total,
            **kwargs)

class CategoryListView(ListView):
    model = Category
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        return super().get_context_data(
            expenses = Expense.objects.values('category').annotate(category_sum = Sum('amount'))
            .values('category__name','category_sum','category__id'),
            **kwargs)

expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'expenses:category-create' %}">add</a>

<table border="1">
	<thead>
		<tr>
			<th>name</th>
			<th>expenses</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
		{% for obj in expenses %}
		<tr>
			<td>
				{{ obj.category__name }}
			</td>
			<td>
				{{ obj.category_sum|floatformat:2 }}
			</td>
			<td>
				<a href="{% url 'expenses:category-edit' obj.category__id %}">edit</a>
				<a href="{% url 'expenses:category-delete' obj.category__id %}">delete</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'expenses:expense-create' %}">add</a>

<form method="get" action="">
  {{form.as_p}}
  <button type="submit">search</button>
</form>
<br>
<table border="1">
	<caption>Expenses</caption>
	<thead>
	  <tr>
		<th>no.</th>
		<th>category</th>
		<th>name</th>
		<th>amount</th>
		<th>date</th>
		<th>actions</th>
	  </tr>
	</thead>
	<tbody>

	{% for obj in object_list %}
	  <tr>
		<td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
		<td>{{ obj.category|default:"-" }}</td>
		<td>{{ obj.name|default:"-" }}</td>
		<td>{{ obj.amount|floatformat:2 }}</td>
		<td>{{obj.date}}</td>
		<td>
		  <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
		  <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
		</td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>

{% include "_pagination.html" %}
<hr>

<table border="1">
  <caption>Summary per category</caption>
  <tr>
    {% for category, total in summary_per_category.items %}
	<tr>
		<td>{{category}}:</td>
		<td>{{total|floatformat:2}}</td>
	</tr>
	{% endfor %}
  </tr>
</table>

<hr>

<table border="1">
  <caption>Total amount spent</caption>
  <tr>
		<td>{{total|floatformat:2}}</td>
  </tr>
</table>

<hr>

<table border="1">
  <caption>Summary per month-year</caption>
  <th>month</th>
  <th>year</th>
  <th>summary</th>
  <tr>
    {% for item in summary_per_date %}
	<tr>
		<td>{{ item.month }}</td>
		<td>{{ item.year }}</td>
		<td>{{ item.summary|floatformat:2 }}</td>
	</tr>
	{% endfor %}
  </tr>
</table>

{% endblock %}

project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'expenses:expense-list' %}">Expenses</a> | 
	<a href="{% url 'expenses:category-list' %}">Categories</a> | 
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}